const ZOOM_MIN = 0.5;
const ZOOM_MAX = 3.0;
const ZOOM_STEP = 0.05;
const BROWSER_ZOOM_MIN = 0.25;
const BROWSER_ZOOM_MAX = 5.0;
const BROWSER_ZOOM_STEP = 0.01;
const DEFAULT_METHOD = 'browser-zoom';
const DEFAULT_LEVEL = 1.0;
const DEFAULT_DEBUG_HIGHLIGHT = false;
const POPUP_BUTTON_STEP_MIN = 0.01;
const POPUP_BUTTON_STEP_MAX = 0.5;
const DEFAULT_POPUP_BUTTON_STEP = 0.05;

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    ZOOM_MIN,
    ZOOM_MAX,
    ZOOM_STEP,
    BROWSER_ZOOM_MIN,
    BROWSER_ZOOM_MAX,
    BROWSER_ZOOM_STEP,
    DEFAULT_METHOD,
    DEFAULT_LEVEL,
    DEFAULT_DEBUG_HIGHLIGHT,
    POPUP_BUTTON_STEP_MIN,
    POPUP_BUTTON_STEP_MAX,
    DEFAULT_POPUP_BUTTON_STEP
  };
}
